version: '3.5'
services:
  sql_server:
    build: sql_server
    command: /bin/bash startup.sh
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QwErTy123!
  web:
    build: web
    command: python run.py
    ports:
    - 5000:5000
    depends_on:
      - sql_server

