version: '3.5'
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    command: /bin/bash /usr/src/app/startup.sh
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QwErTy123!
    volumes:
    - ./sql_server:/usr/src/app
  web:
    build: web
    command: python run.py
    ports:
    - 5000:5000
    depends_on:
      - sql_server
